version: '3'


services:
  flaskapp:
    build: ./flaskapp-docker
    ports:
      - "8000:8000"
    #environment:
     # - SEREVER_NAME=0.0.0.0
    command: python3 app.py
    restart: always